spring.application.name=E-Commerce_Store

spring.jpa.hibernate.ddl-auto=update
spring.datasource.url=jdbc:mysql://localhost:3306/ecommerce
spring.datasource.username=root
spring.datasource.password=Panditg@11111
spring.datasource.driver-class-name=com.mysql.cj.jdbc.Driver

#whatever SQL queries execurte would be print in the output
spring.jpa.show-sql=true 